<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0;net10.0;net8.0;net9.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Kj.Functional.Lib.Extensions</PackageId>
        <Version>0.3.0-dev001</Version>
        <PackageVersion>0.3.0-dev001</PackageVersion>
        <Authors>K. Jablonski</Authors>
        <Company>---</Company>
        <Title>Functional extensions library</Title>
        <Copyright>2026</Copyright>
        <PackageDescription>Small functional extensions library for C#</PackageDescription>
        <PackageProjectUrl>https://github.com/krjab/Functional.Lib.Extensions</PackageProjectUrl>
        <RepositoryUrl>https://github.com/krjab/Functional.Lib.Extensions.git</RepositoryUrl>
        <PackageTags>CSharp; Functional; Kj.Functional.Lib</PackageTags>
        <SuppressXamlWarnings>1591</SuppressXamlWarnings>
    </PropertyGroup>

    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <AnalysisLevel>latest</AnalysisLevel>
        <AnalysisMode>All</AnalysisMode>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <CodeAnalysisTreatWarningsAsErrors>true</CodeAnalysisTreatWarningsAsErrors>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
    </PropertyGroup>   
    
    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <NoWarn>1701;1702;1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../README.md" Pack="true" PackagePath="/" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Kj.Functional.Lib" Version="0.2.8" />
    </ItemGroup>
</Project>
