name: NuGet Generation

on:
  push:
    branches: 
      - master
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore         
        
      - name: Build solution and generate NuGet package
        run: dotnet pack -c Release -o out  Kj.Functional.Lib/

      - name: Push generated package to GitHub registry
        run: dotnet nuget push out/*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
